config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  
  get '/' => 'posts#index', as: 'posts_index'
  get '/new' => 'posts#new', as: 'posts_new'
  get '/show_post/:post_id' => 'posts#show_post', as: 'posts_showpost'
  get '/show' => 'posts#show', as: 'posts_show'
  get '/destroy/:post_id' => 'posts#destroy', as: 'posts_destroy'
  get '/edit/:post_id' => 'posts#edit', as: 'posts_edit'
  
  post '/create' => 'posts#create', as: 'posts_create'
  patch '/upload/:post_id' => 'posts#upload', as: 'posts_upload'
  
  post '/posts/:post_id/comments/cmtcreate'=> 'posts#cmtcreate', as: 'cmt_create'
  get '/posts/:post_id/comments/:reply_id' => 'posts#cmtdestroy', as: 'cmt_destroy'
  get '/posts/:post_id/cmtedit/:reply_id' => 'posts#cmtedit', as: 'cmt_edit'
  post '/posts/:post_id/cmtupload/:reply_id' => 'posts#cmtupload', as: 'cmt_upload'
  
  post '/comments/:reply_id/recomments/recreate' => 'posts#recreate', as: 're_create'
  get '/comments/:reply_id/recomments/:rereply_id' => 'posts#redestroy', as: 're_destroy'
  get '/comments/:reply_id/recomments/:rereply_id/reedit' => 'posts#reedit', as: 're_edit'
  post '/comments/:reply_id/recomments/:rereply_id/reupload' => 'posts#reupload', as: 're_upload'
  
  get '/mypage' => 'mypage#mypage_index'
  get '/test' => 'posts#test'
  
  get '/subject' => 'posts#subject', as: 'posts_subject'
  post '/subject_show' => 'posts#subject_show'
  
  get '/posts/:post_id/like/:user_id' => 'posts#like', as: 'posts_like'

end

app/models/like.rb
class Like < ActiveRecord::Base

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :subject
    has_many :replies
    
    has_many :likes
    has_many :users, through: :likes
    
    mount_uploader :image_url, ImageUploader
end

app/models/reply.rb
class Reply < ActiveRecord::Base
    belongs_to :post
    has_many :rereplies
end

app/models/rereply.rb
class Rereply < ActiveRecord::Base
    belongs_to :reply
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    has_many :posts
    def self.search(search)
        # Title is for the above case, the OP incorrectly had 'name'
        where("subname LIKE ? OR professor LIKE ?", "%#{search}%","%#{search}%")
        
    end
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  
  has_many :likes
  has_many :posts, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  # def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_in) do |user_params|
  #     user_params.permit(:name, :email)
  #   end
  # end
  before_action :configure_permitted_parameters, if:  :devise_controller?


protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
    def mypage_index
        @user = User.find(current_user.id)
        @posts = Post.where(user_id: @user.id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    #메인페이지    
    def index
        @posts = Post.order(created_at: :desc).limit(14)
        @rcmposts = Post.order(likecount: :desc).limit(14)
        
    end
    
    #게시글 작성, 수정, 삭제
    def new
        @post = Post.new
        @subjects = Subject.all
        
    
    end
    
    def create
      
        @subjects = Subject.all
        @post=Post.new
        @post.user_id = current_user.id
        @post.title=params[:post][:title]
        @post.content=params[:post][:content]
        @post.subject_id=params[:subject_id]
        @post.subject_subname=params[:subject_subname]
        @post.subject_professor=params[:subject_professor]
        @post.image_url=params[:post][:image_url]
        
        # @post.user_id = current_user.id
        @post.save
    
        
        redirect_to posts_showpost_path(@post)
     
    end
    
    def destroy
        @destroy_post=Post.find(params[:post_id])
        @destroy_post.destroy
        
        redirect_to '/show'
    end
    
    def edit
        @edit_post = Post.find(params[:post_id])
        
    end
    
    def upload
        @upload_post = Post.find(params[:post_id])
        @upload_post.title = params[:post][:title]
        @upload_post.content = params[:post][:content]
        @upload_post.save
        
        redirect_to '/show'
    end


    #게시글 목록, 게시글 보기
    def show
        @subjects = Subject.all
        if params[:search]
        @subjects = Subject.search(params[:search]).order(created_at: :desc)
        else
         @subjects = Subject.all.order('created_at DESC')
        end
    
        @posts=Post.order(created_at: :desc)
    end
    
    def show_prof
    end

    def show_post
        @show_post=Post.find(params[:post_id])
        #@info=Subject.find(params[:subject_id])
        @likecount=Like.where(post_id: params[:post_id]).count
    end
    

    #댓글 쓰기, 댓글 수정, 댓글 삭제 
    
    def cmtcreate
        @comment=Reply.new
        @comment.content=params[:content]
        @comment.post_id=params[:post_id]
        #@comment.is_re_reply=params[:is_re_reply]
        @comment.save
        
        redirect_to :back
    end
    
    def cmtdestroy
        @destroy_cmt=Post.find(params[:post_id]).replies.find(params[:reply_id])
        @destroy_cmt.destroy
        
        redirect_to :back
    end
    
    def cmtedit
        @edit_cmt= Post.find(params[:post_id]).replies.find(params[:reply_id])
        @post = Post.find(params[:post_id])
        
    end
    
    def cmtupload
        @upload_cmt = Post.find(params[:post_id]).replies.find(params[:reply_id])
        @upload_cmt.content = params[:content]
        @post = Post.find(params[:post_id])
        @upload_cmt.save
        
        redirect_to posts_showpost_path(@post)
       
    end
    

    #대댓글 쓰기, 대댓글 수정, 대댓글 삭제 
    
    def recreate
        @recomment=Rereply.new
        @recomment.content=params[:content]
        @recomment.reply_id=params[:reply_id]
        @recomment.save
        redirect_to :back
    end
    
    def redestroy
        @destroy_recmt = Reply.find(params[:reply_id]).rereplies.find(params[:rereply_id])
        @destroy_recmt.destroy
        
        redirect_to :back
    end

    def reedit
        @edit_recmt=Reply.find(params[:reply_id]).rereplies.find(params[:rereply_id])
        @comment = Reply.find(params[:reply_id])
    end
 
    def reupload
        @edit_upload=Reply.find(params[:reply_id]).rereplies.find(params[:rereply_id])
        @edit_upload.content=params[:content]
        @post = Reply.find(params[:reply_id]).post.id
        @comment = Reply.find(params[:reply_id])
        @edit_upload.save
        
        redirect_to posts_showpost_path(@post)
    end
    
    #학과 과목 교수 카테고리
    def subject
        @subjects = Subject.all
        if params[:search]
        @subjects = Subject.search(params[:search]).order(created_at: :desc)
        else
        @subjects = Subject.all.order('created_at DESC')
        end
    
        @posts=Post.order(created_at: :desc)
       
    end
    
    def subject_show
        @subject = Subject.where(subname: params[:subname])
    end

    #좋아요
    def like
        @like = Like.new
        @like.post_id=params[:post_id]
        @like.user_id=params[:user_id]
        @like.save
        
        @postlike = Post.find(params[:post_id])
        @postlike.likecount += 1
        @postlike.save
        
        redirect_to :back
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/cmtedit.html.erb
댓글 수정 페이지<br><br>

<%= form_tag(cmt_upload_path(post_id: @post.id, reply_id: @edit_cmt.id), :method => "post") do %>
     <%= text_field_tag :content,  @edit_cmt.content %>
     <%= submit_tag "Reply", :name => nil %>
<%end%>
     

app/views/posts/edit.html.erb
<html>
    <head>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
      <!-- your custom css -->
      <link rel="stylesheet" href="css/custom.css">
    </head>
    <body class="bg-faded">
        <a  href="/" class="header d-flex justify-content-start align-items-end pl-2 pl-md-5 mb-5", lang="en">
            SOGANG  WISEMAN
        </a>
        <section class="container">
            <div class="col-12 col-md-8 push-md-2">
                <h1>게시글 수정하기</h1><br>
                <%= form_for @edit_post, url: posts_upload_path do |f| %>
                    제목: <%=f.text_field :title, :value => @edit_post.title, :cols => 100, :class => "col-12"%><br><br>
                    내용: <br><%=f.text_area :content, :value => @edit_post.content, :cols => 100, :rows => 20, :class => "col-12" %><br><br>
                    <%=f.submit '작성', class:"write btn btn-outline-success my-2 my-sm-0"%>
                <%end%><br><br>
                
                <%= link_to 'menu', posts_index_path%>
            </div>
            <footer class="footer my-5">
            <p class="copyright">&copy; 2017 Likelion Sogang</p>
        </footer>
        </section>
        
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>서강지식인</title>
  <!-- fonts -->
  <link href="http://fonts.googleapis.com/earlyaccess/hanna.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css">
  <!-- bootstrap css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <!-- your custom css -->
  <link rel="stylesheet" href="css/custom.css">
  
</head>
<body style="height: 150vh;  bg-faded">
    <div class="header justify-content-start align-items-end pl-3">
      <div class="admin pr-3">
        
        <% if user_signed_in? %>
          <a href="/mypage" class="my_page mr-2">
            My page
          </a>
            <%=link_to(destroy_user_session_path, :method => :delete) do %>
              로그아웃
            <%end%>
        <% else %>
          <%=link_to '로그인', user_session_path%>
          <a href='/users/sign_up'>회원가입</a>
        <%end%>
        
        
      </div>
      
      <a href="/" class="title d-flex">
        SOGANG  WISEMAN
    </a>
    </div>
    
  
  <nav class = "search navbar navbar-light justify-content-center align-items-center mb-3">
    <%= form_tag(posts_show_path, :method => "get", id: "search-form", :class=> "form-inline") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search 과목/교수명", :class=>"form-control mr-sm-2"  %>
    <%= submit_tag "Search", :name => nil, :class=>"btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </nav>
<div class="container">
    <ul class="menu nav justify-content-center row">
      <li class="nav-item col-4">
        <%= link_to 'list', posts_show_path, :class=>"nav-link" %>
      </li>
      <li class="nav-item col-4">
        <a class="nav-link" href="/subject">과목</a>
      </li>
      <li class="nav-item col-4">
        <a class="nav-link" href="#">기타</a>
      </li>
    </ul>
    <div class='new_post d-flex justify-content-end my-4'>
    <%= link_to '글쓰기', posts_new_path, :class=>"d-block write-link px-3 py-2" %>
    </div>
    <div class="posts d-flex mb-10">
      <div class="recent col-12 col-md-6 mb-3 mb-md-0">
        <h3>최신글</h3>
        <div class="post_box">
        <% @posts.each do |x|%>
          <a href='/show_post/<%=x.id%>' class="post_list d-block p-1"><%=x.title%></a><br>
        <%end%>
        </div>
      </div>
      <div class="recommended col-12 col-md-6">
         <h3>추천글</h3>
        <div class="post_box">
          <% @rcmposts.each do |x|%>
            <a href='/show_post/<%=x.id%>' class="post_list d-block p-1"><%=x.title%></a><br>
          <%end%>
        </div>
      </div>
    </div>
    <footer class="col-12 col-md-8 push-2 push-sm-5 py-5">
    <p class="copyright">&copy; 2017 Likelion Sogang</p>
  </footer>
</div>

<div class = 'suggestion'>
    
</div>

    
</div>
  

  
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/new.html.erb
<html>
    <head>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
      <!-- your custom css -->
      <link rel="stylesheet" href="css/custom.css">
    </head>
    <body class="bg-faded">
        <a  href="/" class="header d-flex justify-content-start align-items-end pl-2 pl-md-5 mb-5", lang="en">
            SOGANG  WISEMAN
        </a>
        <section class="container">
            <div class="col-12 col-md-8 push-md-2">
                <h1>새 글 쓰기</h1><br>
                <%= form_for @post, url: posts_create_path, multipart: true do |f|%>
                
                          <!--과목,전공,교수 선택-->
                      <%#= f.collection_select :subject_id, @subjects, :id, :subname %><br>
                    <select name="post[subject_id]">
                        <% @subjects.uniq.each do |subject| %>
                            <option value="<%= subject.id %>"><%= subject.subname %>(<%= subject.professor %>)</option>
                        <% end %>
                    </select>
                    <br>
                    
                    제목: <%=f.text_field :title, :class => "col-12" %><br><br>
                    내용: <br><%=f.text_area :content, :cols => 100, :rows => 20, :class => "col-12" %><br><br>
                    <%= f.file_field :image_url, accept: 'image/*'%>
                    <%=f.submit '작성', class:"write btn btn-outline-success my-2 my-sm-0"%>
            
  <%end%>
                
                <%= link_to 'menu', posts_index_path%>
            </div>
            <footer class="footer my-5">
            <p class="copyright">&copy; 2017 Likelion Sogang</p>
        </footer>
        </section>
        
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

app/views/posts/reedit.html.erb
 <%= form_tag(re_upload_path(reply_id: @comment.id, rereply_id: @edit_recmt.id), :method => "post") do %>
                <%= text_field_tag :content, @edit_recmt.content %>
                <%= submit_tag "reply", :name => nil %>
                <%end%>

app/views/posts/show.html.erb
<html>
    <head>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
      <!-- your custom css -->
      <link rel="stylesheet" href="css/custom.css">
    </head>
    <body class="bg-faded">
        <a  href="/" class="header d-flex justify-content-start align-items-end pl-2 pl-md-5 mb-5", lang="en">
            SOGANG  WISEMAN
        </a>
        <section class="container">
            <h1>게시글 리스트</h1>
           
       
            <%= form_tag(posts_show_path, :method => "get", id: "search-form", :class=>"form-inline search mb-3") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search 과목 / 교수명", :class=> "form-control mr-sm-2" %>
                <%= submit_tag "Search", :name => nil, :class=>"btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
            
            <%@posts.each do |onepost|%>
                <h2>title: <a href='/show_post/<%=onepost.id%>'><%=onepost.title%></a></h2>
            <%end%>
            
            <%= link_to 'menu', posts_index_path%>
            <!--글 제목, 내용, 댓글 대댓글 보여주는-->
            <footer class="footer my-5 d-flex justify-content-center">
            <p class="copyright">&copy; 2017 Likelion Sogang</p>
        </footer>
        </section>
        
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

app/views/posts/show_post.html.erb
<!--글 제목, 내용, 댓글 대댓글 보여주는-->

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>서강지식인</title>
  <!-- fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css">
  <!-- bootstrap css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <!-- your custom css -->
  <!--<link rel="stylesheet" href="/app/assets/stylesheets/custom.css">-->
  <link rel="stylesheet" href="css/custom.css">
  
</head>
<body style="bg-faded">
    <a href="/" class="header d-flex justify-content-start align-items-end pl-3 mb-5">
        SOGANG  WISEMAN
    </a>
    <div class="container">
        
        <div class="post_title mb-3 col-12 col-md-8 push-0 push-sm-2">
          <h2>제목: <%=@show_post.title%>  <%#@info.subname%></h2>
        </div>
        <div class="post_content mb-3 col-12 col-md-8 push-0 push-sm-2">
            <h4>내용: <%=@show_post.content%></h4>
        </div>
        
        <%= image_tag @show_post.image_url%>
        
        <div class="delete_update col-12 col-md-8 push-4 push-sm-5 push-md-6 push-lg-7 mb-3">
            <%#=form_tag(posts_like_path(post_id: post_id, user_id: user_id), :method => "post") do %>
                <%#= submit_tag "♥ like", :name => nil %>
            <%#end%>
            <%= link_to "♥ like #{@likecount}", posts_like_path(post_id: @show_post.id, user_id: current_user.id), :class => "post_delete btn btn-outline-success my-2 my-sm-0" %>
    
            <a href='/destroy/<%=@show_post.id%>' class="post_delete btn btn-outline-success my-2 my-sm-0">글 삭제</a>
            <a href='/edit/<%=@show_post.id%>'  class="post_update btn btn-outline-success my-2 my-sm-0">글 수정</a>
        </div>
        
        <div class="comments col-12 col-md-8 push-0 push-sm-2 mb-3">
          댓글<br>
        <!-- 댓글 보여주는 창-->
        <%@show_post.replies.each do |onereply|%>
        
            <span class="comment d-block"><%= onereply.content %>
            <a href='/posts/<%=@show_post.id%>/comments/<%=onereply.id%>' class="btn_delete ml-1">x</a>
            <a href='/posts/<%=@show_post.id%>/cmtedit/<%=onereply.id%>' class="btn_delete ml-1">edit</a>
            </span>
             <!--대댓글 보여주기-->
            <%onereply.rereplies.each do |rereply|%>
                <span class="comment d-block pl-4">
                    <%= rereply.content%>
                    
                    <a href='/comments/<%=onereply.id%>/recomments/<%=rereply.id%>' class="btn_delete ml-1">x</a>
                    <a href='/comments/<%=onereply.id%>/recomments/<%=rereply.id%>/reedit' class="btn_delete ml-1">edit</a>
                </span> 
            <%end%>
        <!--대댓글 작성-->
            <%= form_tag(re_create_path(reply_id: onereply.id), :method => "post") do %>
                <%= text_field_tag :content, "", placeholder:"대댓글 입력", class: "reply_tag mb-2" %>
                <%= submit_tag "reply", :name => nil, :class => "btn_reply btn btn-outline-success my-2 my-sm-0" %>
            <%end%>
        <%end%>
        
        <br><br>
        <!-- 댓글 작성 -->
        <%= form_tag(cmt_create_path, :method => "post", post_id: @show_post.id) do %>
             <%= text_field_tag :content, "", placeholder:"댓글 입력", class: "Reply_tag"%>
             <%= submit_tag "Reply", :name => nil, :class => "btn_reply btn btn-outline-success my-2 my-sm-0" %>
             
        <%end%>    
        </div>
        

        <%=link_to 'menu', posts_index_path%>
        <footer class="footer my-5 d-flex justify-content-center">
            <p class="copyright">&copy; 2017 Likelion Sogang</p>
        </footer>
    </div>

  <h1><%=link_to '글목록으로 가기', posts_show_path%></h1>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/subject.html.erb
<html>
    <head>
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
      <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
      <!-- your custom css -->
      <link rel="stylesheet" href="css/custom.css">
    </head>
    <body class="bg-faded">
        <a  href="/" class="header d-flex justify-content-start align-items-end pl-2 pl-md-5 mb-5", lang="en">
            SOGANG  WISEMAN
        </a>
        <section class="container">
            <nav class = "search navbar navbar-light justify-content-center align-items-center mb-3">
    <%= form_tag(posts_subject_path, :method => "get", id: "search-form", :class=> "form-inline") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search 과목", :class=>"form-control mr-sm-2"  %>
    <%= submit_tag "Search", :name => nil, :class=>"btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
</nav>

<%@array=[]%>
<% @subjects.each do |x| %>
  
    <%@array << x.subname.to_s%>
  
<%end%>

<%@array.uniq.each do |subject|%>
    <form action = 'subject_show' method='post'>
        <%=subject%>
        <input type ='hidden' name ='subname' value ='<%=subject%>'>
        <input type ='submit' value ='go!'><br>
    </form>
<%end%>
            <footer class="footer my-5 d-flex justify-content-center">
            <p class="copyright">&copy; 2017 Likelion Sogang</p>
        </footer>
        </section>
        
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

app/views/posts/test.html.erb
이거 테스트 페이지

<%@s.each do |row|%>
    <%= row.subname%><br>
<%end